<?php
declare(strict_types=1);

final class Env
{
    public static function load(string $envFile): void
    {
        if (!is_file($envFile)) return;

        $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        if ($lines === false) return;

        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) continue;

            $pos = strpos($line, '=');
            if ($pos === false) continue;

            $key = trim(substr($line, 0, $pos));
            $val = trim(substr($line, $pos + 1));
            if ($key === '') continue;

            if (
                (str_starts_with($val, '"') && str_ends_with($val, '"')) ||
                (str_starts_with($val, "'") && str_ends_with($val, "'"))
            ) {
                $val = substr($val, 1, -1);
            }

            putenv($key . '=' . $val);
            $_ENV[$key] = $val;
        }
    }

    public static function write(string $envFile, array $data): void
    {
        if (in_array(strtolower((string)(getenv('ENV_ONLY') ?: '0')), ['1','true','yes','on'], true)) {
            throw new RuntimeException('ENV_ONLY=1: settings write disabled');
        }

        $dir = dirname($envFile);
        if (!is_dir($dir)) @mkdir($dir, 0775, true);

        $lines = ['# Auto-generated by Settings page', ''];
        foreach ($data as $k => $v) {
            if (!preg_match('/^[A-Z0-9_]+$/', (string)$k)) continue;
            $v = str_replace('"', '\"', (string)$v);
            $lines[] = $k . '="' . $v . '"';
        }

        $tmp = $envFile . '.tmp';
        file_put_contents($tmp, implode(PHP_EOL, $lines) . PHP_EOL);
        @chmod($tmp, 0660);
        rename($tmp, $envFile);
    }
}
